/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_InstanceInfoController */

#ifndef _Included_com_example_InstanceInfoController
#define _Included_com_example_InstanceInfoController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_InstanceInfoController
 * Method:    getCpuInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_InstanceInfoController_getCpuInfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

